linter:
  rules:
    
    parameter_assignments: true
    
    # DO name libraries, packages, directories, and source files using
    lowercase_with_underscores: true

    # Useless containers
    avoid_unnecessary_containers: true

    # Immutable widget must have final fields and constructor must be const
    prefer_final_fields: true
    prefer_const_constructors_in_immutables: true

    # Make constructors the first thing in every class
    sort_constructors_first: false 
    
    directives_ordering: false

    sort_child_properties_last: false

    # Good packages document everything
    public_member_api_docs: false

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: false

    # Back to the 80s
    lines_longer_than_80_chars: true

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util casses are awesome!
    avoid_classes_with_only_static_members: false

    unnecessary_new: true

analyzer:
    errors:
        missing_required_param: error
        parameter_assignments: error
        avoid_unnecessary_containers: error
        unnecessary_new: warning
    

